   1 #! /usr/bin/env python
   2 #  -*- coding: utf-8 -*-
   3 #
   4 # GUI module generated by PAGE version 4.25.1
   5 #  in conjunction with Tcl version 8.6
   6 #    Oct 04, 2019 08:45:56 PM -0300  platform: Windows NT
   7 
   8 import sys
   9 
  10 try:
  11     import Tkinter as tk
  12 except ImportError:
  13     import tkinter as tk
  14 
  15 try:
  16     import ttk
  17     py3 = False
  18 except ImportError:
  19     import tkinter.ttk as ttk
  20     py3 = True
  21 
  22 import _support
  23 
  24 def vp_start_gui():
  25     '''Starting point when module is the main routine.'''
  26     global val, w, root
  27     root = tk.Tk()
  28     top = Toplevel1 (root)
  29     _support.init(root, top)
  30     root.mainloop()
  31 
  32 w = None
  33 def create_Toplevel1(root, *args, **kwargs):
  34     '''Starting point when module is imported by another program.'''
  35     global w, w_win, rt
  36     rt = root
  37     w = tk.Toplevel (root)
  38     top = Toplevel1 (w)
  39     _support.init(w, top, *args, **kwargs)
  40     return (w, top)
  41 
  42 def destroy_Toplevel1():
  43     global w
  44     w.destroy()
  45     w = None
  46 
  47 class Toplevel1:
  48     def __init__(self, top=None):
  49         '''This class configures and populates the toplevel window.
  50            top is the toplevel containing window.'''
  51         _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
  52         _fgcolor = '#000000'  # X11 color: 'black'
  53         _compcolor = '#d9d9d9' # X11 color: 'gray85'
  54         _ana1color = '#d9d9d9' # X11 color: 'gray85'
  55         _ana2color = '#ececec' # Closest X11 color: 'gray92'
  56         self.style = ttk.Style()
  57         if sys.platform == "win32":
  58             self.style.theme_use('winnative')
  59         self.style.configure('.',background=_bgcolor)
  60         self.style.configure('.',foreground=_fgcolor)
  61         self.style.configure('.',font="TkDefaultFont")
  62         self.style.map('.',background=
  63             [('selected', _compcolor), ('active',_ana2color)])
  64 
  65         top.geometry("242x168+344+142")
  66         top.title("New Toplevel")
  67         top.configure(background="#d9d9d9")
  68 
  69         self.TEntry1 = ttk.Entry(top)
  70         self.TEntry1.place(relx=0.207, rely=0.238, relheight=0.125
  71                 , relwidth=0.529)
  72         self.TEntry1.configure(takefocus="")
  73         self.TEntry1.configure(cursor="ibeam")
  74 
  75         self.TButton1 = ttk.Button(top)
  76         self.TButton1.place(relx=0.124, rely=0.536, height=24, width=77)
  77         self.TButton1.configure(takefocus="")
  78         self.TButton1.configure(text='''Tbutton''')
  79 
  80         self.TButton2 = ttk.Button(top)
  81         self.TButton2.place(relx=0.496, rely=0.536, height=24, width=77)
  82         self.TButton2.configure(takefocus="")
  83         self.TButton2.configure(text='''Tbutton''')
  84 
  85 if __name__ == '__main__':
  86     vp_start_gui()